### ISSUE TITLE
Is This Still Helpful for El Capitan Users?

### ISSUE THREAD

**Issue by jcmiller11** [mariociabarra/wifriedx#5]
Your README.md simply says "Band-aid for Yosemite WiFi issues"

Are these issues still present in more recent versions of OS X?

**Comment by mariociabarra** [comment]
Apple has tuned the parameters so that the negative effects are negligible.   While there is still frequency hopping of the WiFi interface between channel 149 (the apple chosen AWDL channel) and the active WiFi channel (your connected access point channel), they've reduced the length of time which the AWDL interface is communicating in discovery mode (discovering other devices).  In other words, I wouldn't highly recommend installing WiFriedX on the 10.11.3+ El Capitain.  While there's some advantages of disabling it all together, the problem has been minimized enough that it's no longer an issue for the general public as it was previously.
